name: restadmin
version: 1.0.7+11
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.7.0

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_staggered_animations: ^1.1.1
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  pinput: ^5.0.1
  shimmer: ^3.0.0
  webview_flutter: ^4.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  timer_count_down: ^2.2.2
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  android: true
  ios: true
  web: false
  image: images/icon.png
  fullscreen: true
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"
    image: images/icon.png
    #color_dark: "#08998c"
  android_gravity: center
  ios_content_mode: center
flutter:
  uses-material-design: true
  assets:
    - images/
